# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-15 12:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zjapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='\u7c7b\u522b\u540d\u79f0', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='\u90e8\u95e8\u540d\u79f0', max_length=255, null=True)),
                ('mark', models.TextField(blank=True, help_text='\u5907\u6ce8', null=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='mark',
            field=models.TextField(blank=True, help_text='\u5907\u6ce8', null=True),
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='zjapp.DepartmentModel'),
        ),
        migrations.AddField(
            model_name='user',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='zjapp.CategoryModel'),
            preserve_default=False,
        ),
    ]
